spring:
  application:
     name: springcloud-admin
  security:
    user:
      name: "admin"
      password: "123456"

server:
  port: 8760
  servlet:
    context-path: /

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    statusPageUrlPath: /swagger-ui.html
    #  如果项目配置有 server.servlet.context-path 属性，想要被 spring boot admin 监控，就要配置以下属性
    metadata-map:
      user.name: "admin"         #These two are needed so that the server
      user.password: "123456" #can access the protected client endpoints
#      management:
#        context-path: ${server.servlet.context-path}/actuator
#    health-check-url: http://localhost:${server.port}${server.servlet.context-path}/actuator/health
#    status-page-url: http://localhost:${server.port}${server.servlet.context-path}/actuator/info
#    home-page-url: http://localhost:${server.port}/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


