spring:
  profiles:
    active: github
  datasource:
    url: jdbc:mysql://localhost:3306/apolloconfigdb? characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  file: /data/logs/apollo-assembly.log
server:
  port: 8761
